# Generated by Django 4.2.6 on 2023-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='library_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
