# Generated by Django 4.2.6 on 2023-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_userprofile_library_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='library_card_number',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
