# Generated by Django 4.2.6 on 2023-11-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0003_albuminstance_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albuminstance',
            name='return_date',
        ),
    ]
