# Generated by Django 4.2.6 on 2023-11-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0004_remove_albuminstance_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='copies_available',
            field=models.IntegerField(default=0, help_text='Number of copies available'),
        ),
    ]
