# Generated by Django 4.2.6 on 2023-11-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0005_album_copies_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
