# Generated by Django 4.2.6 on 2023-11-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0006_artist_album_image_artist_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album_image',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
