# Generated by Django 4.2.6 on 2023-11-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0008_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuminstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], default='a', max_length=1),
        ),
    ]
