# Generated by Django 4.2.6 on 2023-12-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0017_remove_album_duration_remove_album_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date_of_death',
        ),
    ]
