# Generated by Django 4.2.6 on 2023-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0018_remove_artist_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(blank=True, help_text='Upload an image for this genre', null=True, upload_to='genre_images/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter an album genre (e.g. Country)', max_length=200),
        ),
    ]
