# Generated by Django 4.2.6 on 2023-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0019_genre_genre_image_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter an album genre (e.g., Country)', max_length=200),
        ),
    ]
