# Generated by Django 4.2.6 on 2023-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0020_rename_genre_image_genre_image_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images/'),
        ),
    ]
