# Generated by Django 4.2.6 on 2023-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0023_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancart',
            name='address',
            field=models.TextField(max_length=50),
        ),
    ]
