# Generated by Django 4.2.6 on 2023-12-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0024_alter_loancart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancart',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
