# Generated by Django 4.2.6 on 2023-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0026_rename_name_loancart_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancart',
            name='albums',
        ),
        migrations.AddField(
            model_name='loancart',
            name='AlbumInstance',
            field=models.ManyToManyField(to='MelodyMatrix.albuminstance'),
        ),
    ]
