# Generated by Django 4.2.6 on 2023-12-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyMatrix', '0027_remove_loancart_albums_loancart_albuminstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='album',
            new_name='AlbumInstance',
        ),
    ]
